/// Flutter icons GreenhousesIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GreenhousesIcons
///      fonts:
///       - asset: fonts/GreenhousesIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class GreenhousesIcons {
  GreenhousesIcons._();

  static const _kFontFam = 'GreenhousesIcons';
  static const _kFontPkg = null;

  static const IconData home_tab = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assistant_tab = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_tab = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
